#define __ESCA_sendfile 71
#define __ESCA_shutdown 210
#define __ESCA_close 57
#define __ESCA_write 64
#define __ESCA_sendto 206
#define __ESCA_sendmsg 211
#define __ESCA_accept4 242
#define __ESCA_read 63
#define __ESCA_writev 66