#define __ESCA_sendfile 40
#define __ESCA_shutdown 48
#define __ESCA_close 3
#define __ESCA_write 1
#define __ESCA_sendto 44
#define __ESCA_sendmsg 46
#define __ESCA_accept4 288
#define __ESCA_read 0
#define __ESCA_writev 20